job:  #11444  Fixed masl typo in wasl2xtuml.  Added 2 pass support so that objects can be defined and then refined around relationships.  Dealt with key letters when names are not present.

diff --git a/bin/wasl2xtuml b/bin/wasl2xtuml
--- a/bin/wasl2xtuml
+++ b/bin/wasl2xtuml
@@ -57,7 +57,7 @@ if [[ $OUT_DIR == "" ]]; then OUT_DIR=.; fi
 # make the output directory if ther is one
 if [[ $OUT_DIR != "" ]]; then
     if ! mkdir -p $OUT_DIR; then
-        echo "-masl2xtuml: ERROR could not create directory '$OUT_DIR'" 1>&2
+        echo "-wasl2xtuml: ERROR could not create directory '$OUT_DIR'" 1>&2
         exit 1
     fi
 fi
